name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch
  workflow_dispatch:  # Allows manual triggering

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Copy assets to public directory
        run: |
          mkdir -p public/assets
          cp -r assets/* public/assets/ || true
          echo "$(date)" > public/build-timestamp.txt
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2