name: "Issue and PR Labeler"
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

# Required permissions for the labeler to work properly
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GH_TOKEN }}"
        configuration-path: .github/labeler-config.yml
        sync-labels: false
        dot: false
