name: PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          types: feat,fix,docs,style,refactor,perf,test,build,ci,chore,revert

      - name: Lint Code Base
        uses: github/super-linter@v7
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          VALIDATE_JAVASCRIPT_ES: true
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
