name: Releases
on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Add this step to convert Dependabot PR titles to conventional commit format
      - name: Process commit message
        id: process_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Original commit message: $COMMIT_MSG"

          # Check if it's a Dependabot commit and transform it
          if [[ "$COMMIT_MSG" == "Bump "* ]]; then
            CONVENTIONAL_MSG="chore(deps): $COMMIT_MSG"
            echo "Transformed to: $CONVENTIONAL_MSG"
            echo "commit_message=$CONVENTIONAL_MSG" >> $GITHUB_OUTPUT
          else
            echo "commit_message=$COMMIT_MSG" >> $GITHUB_OUTPUT
          fi

      # Check for existing tag to handle the case where the tag already exists
      - name: Check if tag exists
        id: check_tag
        run: |
          # Get latest version from package.json
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          # Check if tag v{PACKAGE_VERSION} exists
          if git tag -l "v$PACKAGE_VERSION" | grep -q "v$PACKAGE_VERSION"; then
            echo "Tag v$PACKAGE_VERSION already exists, will use skip_tag_action=true"
            echo "skip_tag_action=true" >> $GITHUB_OUTPUT
          else
            echo "Tag v$PACKAGE_VERSION does not exist"
            echo "skip_tag_action=false" >> $GITHUB_OUTPUT
          fi

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6.0.0
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          version-file: './releases.json,./package.json'
          git-message: '{version} [skip ci]'
          git-user-name: 'Automated'
          git-user-email: 'actions@github.com'
          preset: 'angular'
          output-file: 'CHANGELOG.md'
          release-count: 0
          skip-on-empty: false
          skip-version-file: false
          skip-tag: ${{ steps.check_tag.outputs.skip_tag_action }}
          types: |
            {"feat": {"name": "Features"},
             "fix": {"name": "Bug Fixes"},
             "perf": {"name": "Performance Improvements"},
             "docs": {"name": "Documentation"},
             "style": {"name": "Styles"},
             "refactor": {"name": "Code Refactoring"},
             "test": {"name": "Tests"},
             "build": {"name": "Build System"},
             "ci": {"name": "Continuous Integration"},
             "chore": {"name": "Chores"}}

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' && steps.check_tag.outputs.skip_tag_action == 'false' }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: false
          prerelease: false
