name: Update README

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'  # Runs every 3 days at midnight

jobs:
  build:
    name: Update this repo's README
    runs-on: ubuntu-22.04  # Use a different runner
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Cache Blog Data
        uses: actions/cache@v3
        with:
          path: ~/.blog-post-cache
          key: ${{ runner.os }}-blog-cache

      - name: Update blogs
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/manthanank, https://medium.com/feed/@manthanank, https://manthanank.hashnode.dev/feed"  # Use /feed instead of /rss.xml
          max_retries: 3
          retry_delay: 300

      - name: WakaTime Language Insights
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          LANG_COUNT: 10
